name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to Mirror Repo
        run: |
          git remote add mirror https://github.com/arthuray/arthuray.github.io.git
          git push mirror --mirror
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_REPO_TOKEN }}
