name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2

    - name: Push changes to mirror repository
      env:
        MIRROR_REPO_TOKEN: ${{ secrets.MIRROR_REPO_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git remote add mirror https://$MIRROR_REPO_TOKEN@github.com/arthuray/arthuray.github.io.git
        git push mirror main --force
